# Generated by Django 4.0.1 on 2022-01-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('project_manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'project_manager',
            },
        ),
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('purchase_manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'purchase_manager',
            },
        ),
        migrations.CreateModel(
            name='purchase_request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('req_product', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('product_link', models.TextField(blank=True)),
                ('price', models.CharField(max_length=100)),
                ('project_manager', models.CharField(blank=True, max_length=100)),
                ('purchase_manager', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(max_length=200)),
                ('request_date', models.DateTimeField(blank=True)),
                ('approved_date', models.DateTimeField(blank=True)),
                ('purchase_date', models.DateTimeField(blank=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('image', models.TextField(blank=True)),
                ('invoice', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'purchase_request',
            },
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=100)),
                ('uname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
