# Generated by Django 4.0.1 on 2022-01-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_type',
            fields=[
                ('user_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_type',
            },
        ),
    ]
