# Generated by Django 4.0.1 on 2022-01-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_request',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_request',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_request',
            name='request_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
