# Generated by Django 4.0.1 on 2022-01-06 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_alter_purchase_request_approved_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase_request',
            old_name='id',
            new_name='req_id',
        ),
    ]
